name: Daily Stock info

on:
  schedule:
    - cron: "0 13 * * 1-5"
    - cron: "0 19 * * 1-5"
  workflow_dispatch:
    
jobs:
  qod:
    runs-on: ubuntu-latest
    steps:
    - run: |
        QUOTE=$(curl -s http://api.quotable.io/random | jq '"\(.content) - _\(.author)_"')
        curl -s -X POST "${{ secrets.DAILY_DIGEST_URL }}" -d "content=$QUOTE"

