
name: Daily Digest
on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 13 * * 1-5" # monday - friday at 6am
#     - cron: "0 19 * * 1-5" # monday - friday at 12pm
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed
      - name: pip install packages
        run: |
          pip install python-dotenv
          pip install -U git+https://github.com/mariostoev/finviz
      - name: execute py script # run the run.py to get the latest data
        run: |
          python stock_queries.py
      # - name: export index
      #   .... # use crosponding script or actions to help export.
