name: Daily Stock info

on:
  schedule:
    - cron: "0 13 * * 1-5"
    - cron: "0 19 * * 1-5"
  workflow_dispatch:
    
jobs:
  qod:
    runs-on: ubuntu-latest
    steps:
    - run: |
        DAILY_DIGEST=$(curl -s https://memo-stock-bot.herokuapp.com/daily | jq -r '.[] | "\(.name) \n - \(.results) \n" ' | sed 's/"//g')
        curl -s -X POST "${{ secrets.DAILY_DIGEST_URL }}" -d "content=$DAILY_DIGEST"

